common: &common
  adapter: mysql2
  username: root
  password: Gimler12
  host: localhost
  encoding: utf8
  

development:
  <<: *common
  # database: ilab_chamomile_staging
  database: alfa1

production:
  <<: *common
  database: alfa1